server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbootdemo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=TRUE&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mappering/*.xml        #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.demo.entity    # 注意：对应实体类的路径